### ISSUE TITLE
Define criteria for adding a new repo

### ISSUE THREAD

**Issue by orsinium** [DmytroLitvinov/awesome-flake8-extensions#126]
I see that there are some open PRs that are dangling waiting for the project to get mature: #108 #112 #121.  The contributing guide defines maturity as follows:

> If you just created something, wait at least 30 days before submitting. This is to give it some time to mature and ensure it's not just a publish-and-forget type of project.

On practice, however, this definition isn't strictly followed. [From the comments to 108](https://github.com/DmytroLitvinov/awesome-flake8-extensions/pull/108#issuecomment-1265169061):

> I don't have clean points what is "mature". But you are right that it is based on stars and time since creation. I would not close that PR and just give it time.

Hence I have a few suggestions:

1. Probably, the definition of maturity in the [contributing guide](https://github.com/DmytroLitvinov/awesome-flake8-extensions/blob/master/contributing.md) should be adjusted to what we actually follow.
1. If this is time-based, we might use CI to enforce it. For example, [awesome-lint](https://github.com/sindresorhus/awesome-lint) has a [git-repo-age](https://github.com/sindresorhus/awesome-lint/blob/main/rules/git-repo-age.js) rule.
1. I personally think that the specifics of this particular list are such that most of the tools are made once and never updated again, which doesn't mean they are bad. Linter rules usually don't need active maintenance, [unless flake8 team decided to break backward compatibility without any reason](https://github.com/PyCQA/flake8/issues/1759). Also, such little UNIX-way tools, being quite niche, don't usually gain much popularity through Reddit or hackernews. This list **is** how they get traction. Merging such PRs **is** the prerequisite for the project to get mature.

**Comment by DmytroLitvinov** [comment]
Hi @orsinium ,

I added you as a collaborator on the repository. I appreciate your contribution to the repository. 

As for suggestions: do you think we can integrate [git-repo-age](https://github.com/sindresorhus/awesome-lint/blob/main/rules/git-repo-age.js) rule and maybe at least 2 approves from three of us like @sobolevn, you and me as an active collaborator on the repo?

**Comment by sobolevn** [comment]
+ from me

**Comment by orsinium** [comment]
> do you think we can integrate [git-repo-age](https://github.com/sindresorhus/awesome-lint/blob/main/rules/git-repo-age.js) rule

We can give it a try and see what people think of it. I'll see how to activate the rule and send a PR.

> and maybe at least 2 approves from three of us

Sounds good. We have about 2 PRs per month, I certainly can review that 🙃

**Comment by orsinium** [comment]
I've looked into awesome-lint, and I have no idea why this specific rule seems to not work. All rules are supposed to be enabled by default.

**Comment by orsinium** [comment]
I close the issue. The criteria stay the same for now (30+ days of existence), and it's not that important to enforce it with awesome-lint, I certainly can keep track of it myself.

**Comment by DmytroLitvinov** [comment]
Thank you Gram, for your work on that repository 🙇‍♂️
