### ISSUE TITLE
pydoclint for linting Python docstring

### ISSUE THREAD

**Issue by jsh9** [DmytroLitvinov/awesome-flake8-extensions#127]
Hi, I recently wrote a new linter, pydoclint (https://github.com/jsh9/pydoclint), which aims to replace [darglint](https://github.com/terrencepreilly/darglint).

Can I recommend for my linter to be added to your list?

Thank you!

**Comment by orsinium** [comment]
Looks cool, great work :) As per #126, we only add the projects that exist for 30+ days. So, let it boil for a month and bring it in 👍🏿

**Comment by jsh9** [comment]
Thanks @orsinium !  I'll wait for a while then.

**Comment by jsh9** [comment]
Hi @orsinium : it's been a month, and there are already 26 stars to my project.  Let me create a PR to add it to this repo then.
