### ISSUE TITLE
Add flake8-mutable

### ISSUE THREAD

**Issue by vr050714** [DmytroLitvinov/awesome-flake8-extensions#136]
[https://github.com/ebeweber/flake8-mutable](https://github.com/ebeweber/flake8-mutable)

It detects wrong use of mutable objects as default values for arguments.

**Comment by DmytroLitvinov** [comment]
LGTM 👍

**Comment by orsinium** [comment]
Sounds great! Send a PR, please, and I'll be happy to merge :)
