### ISSUE TITLE
List integrations

### ISSUE THREAD

**Issue by sobolevn** [DmytroLitvinov/awesome-flake8-extensions#18]
I suggest to list different integrations. Like here: https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage/integrations.html#editors

What can we list?
- Editors and IDEs plugins
- 3rd party tools like `pytest`
- 3rd party services like `gitlab` / `github` bots, CIs, code quality services, etc

I am going to provide a link to this awesome project from https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage/integrations.html

**Comment by DmytroLitvinov** [comment]
Hello @sobolevn .
There are not a lot of them under our list.
P.S. Provided link is broken.

**Comment by DmytroLitvinov** [comment]
Closed as staled.
