### ISSUE TITLE
Categorize list by category

### ISSUE THREAD

**Issue by DmytroLitvinov** [DmytroLitvinov/awesome-flake8-extensions#2]
It will be great to categorize this list.

Example of categories: security, refactor(or clean code maybe), compatibility py2/py3.

**Comment by discosultan** [comment]
It'd also be nice to have the categorized lists ordered alphabetically (both the categories themselves as well as entries in a category).

**Comment by DmytroLitvinov** [comment]
Hi @discosultan .

Thank you for the proposal.
Added as an issue https://github.com/DmytroLitvinov/awesome-flake8-extensions/issues/4 on project.
