### ISSUE TITLE
Flake8 Extension Deprecation (flake8-type-annotations/flake8-per-file-ignores)

### ISSUE THREAD

**Issue by KyleKing** [DmytroLitvinov/awesome-flake8-extensions#36]
Thanks for putting together this list!

Looking through the links I found that the two extensions below are deprecated (deprecation summary is edited from the respective repo):
- [flake8-type-annotations](https://github.com/sobolevn/flake8-type-annotations) - `Deprecated and is no longer required after flake8 >=3.7. Handled via E225 and E252 violation checks.`
- [flake8-per-file-ignores](https://github.com/snoack/flake8-per-file-ignores) - `Discontinued in favor of the per-file-ignores option built into flake8 >=3.7. But be aware that the built-in option uses different syntax.`

Also, [flake8-putty](https://github.com/jayvdb/flake8-putty) is `flake8>=2,<3` if that should be indicated in the README

**Comment by sobolevn** [comment]
Yes, I am the author of `flake8-type-annotations`, it should be removed.

**Comment by DmytroLitvinov** [comment]
Fixed in https://github.com/DmytroLitvinov/awesome-flake8-extensions/commit/f9358e64235ccb0bc0f10a6fd5ba01ef729be796
