### ISSUE TITLE
Move flake8-mypy to Type annotations

### ISSUE THREAD

**Issue by atollk** [DmytroLitvinov/awesome-flake8-extensions#41]
It seems the flake8-mypy plugin would better be suited under the section "Type annotations".

**Comment by DmytroLitvinov** [comment]
Hi @atollk ,

Yes, you are right.

Would you like to do PR?

**Comment by atollk** [comment]
Sure: https://github.com/DmytroLitvinov/awesome-flake8-extensions/pull/42
