### ISSUE TITLE
Add wemake-python-styleguide

### ISSUE THREAD

**Issue by sobolevn** [DmytroLitvinov/awesome-flake8-extensions#7]
What section should it be in?

https://github.com/wemake-services/wemake-python-styleguide

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn .

First of all, thank you for a really good project.
I think we could create section something like "Extended flake8" or "flake8 framework".
What do you think?

**Comment by sobolevn** [comment]
@DmytroLitvinov sounds good to me!
