### ISSUE TITLE
flake8-commas is deprecated

### ISSUE THREAD

**Issue by sobolevn** [DmytroLitvinov/awesome-flake8-extensions#81]
Related:
- https://github.com/PyCQA/flake8-commas
- https://github.com/wemake-services/wemake-python-styleguide/issues/2276

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn ,
I like the idea of forking the package and continue maintain it.
If I can help somehow - let me know.

**Comment by cruisen** [comment]
However, as said in https://github.com/PyCQA/flake8-commas#flake8-extension-to-enforce-better-comma-placement:

> Note: Black, the uncompromising Python code formatter, or add-trailing-comma can do all this comma insertion automatically. We recommend you use one of those tools instead.

So from my point of view, we are keeping sort of a redundancy here. And hence, what is the motivation to do so?
